# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: public

jobs:
# Please do not rename this job
  build-project:
    name: build copernicus-ui
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          CI: true
          NEXT_PUBLIC_DEFAULT_MODEL: gpt-4o
          NEXT_PUBLIC_SITE_NAME: Copernicus AI
          NEXT_PUBLIC_SITE_URL: ${{ inputs.site-url }}
          NEXT_PUBLIC_USE_PROXIED_API: false
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm ci
          npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 46b76a0f-5f0f-430b-ab34-baa98e8354ad
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/copernicus-ui/config.yaml
          action: upload
